project:
  artifactId: springframework-site
  name: Sagan
  version: X.X.X.X
  description: Sagan website

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

spring:
  template:
    mode: LEGACYHTML5
    cache: false
  jpa:
    ddl_auto: update

security:
  basic:
    path: ""

github:
  client:
    id: fb06c006c2ed62fe9e8b
    secret: 164264e3f6d70c7c21713b7fa64225cb8d6107b2

---

spring:
  profiles: default,site
  main:
    sources: org.springframework.site.web.configuration.ApplicationConfiguration
  search:
    indexer:
      delay: 0
      base_url: http://localhost:8080

---

spring:
  profiles: indexer
  main:
    sources: org.springframework.site.indexer.configuration.IndexerConfiguration
server:
  port: 9000

---

spring:
  profiles: development
search:
  indexer:
    delay: 0
    base_url: https://sagan.cfapps.io
elasticsearch:
  client:
    endpoint: https://qlmsjwfa.api.qbox.io

---

spring:
  profiles: staging,production
search:
  indexer:
    delay: 0
elasticsearch:
  client:
    endpoint: https://qlmsjwfa.api.qbox.io

---

spring:
  profiles: acceptance
  database:
    url: jdbc:hsqldb:mem:acceptancetestdb