project:
  artifactId: spring-io
  name: spring-io
  version: X.X.X.X
  description: spring-io

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:sagan}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    show_sql: false
    hibernate:
      namingstrategy: org.hibernate.cfg.EJB3NamingStrategy

security:
  basic:
    enabled: false
  require_ssl: false
  ignored: 
    - /bootstrap/**
    - /bootstrap-datetimepicker/**
    - /css/**
    - /font-awesome/**
    - /img/**
    - /js/**
    - /error
    - /500
    - /404
    - /project_metadata/**
  headers:
    hsts: domain
  user:
    password: ${ADMIN_PASSWORD:}

github:
  client:
    id: fb06c006c2ed62fe9e8b
    secret: 164264e3f6d70c7c21713b7fa64225cb8d6107b2

elasticsearch:
  client:
    endpoint: ${ELASTICSEARCH_ENDPOINT:http://localhost:9200}
    index: sagan-local

server:
    tomcat:
        # Write access log to target/logs/access_log.YYYY-MM-DD.log
        # See http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/AccessLogValve.html
        accessLogEnabled: true
        accessLogPattern: '%h %l %u %t "%r" %s %b %{Host}i %{Location}o'
        baseDir: ''
        backgroundProcessorDelay: 1

---

spring:
  profiles: site,default
  main:
    sources: io.spring.site.web.configuration.ApplicationConfiguration

---

spring:
  profiles: indexer
  main:
    sources: io.spring.site.indexer.configuration.IndexerConfiguration
search:
  indexer:
    delay: 0
server:
  port: 9000

---

spring:
  profiles: development,staging,performance,production
security:
  require_ssl: true

---

spring:
  profiles: development
search:
  indexer:
    base_url: https://sagan-development.cfapps.io
elasticsearch:
  client:
    index: sagan-development
cache:
  timetolive: 0

---

spring:
  profiles: performance
search:
  indexer:
    base_url: https://sagan-performance.cfapps.io
elasticsearch:
  client:
    index: sagan-performance

---

spring:
  profiles: staging
search:
  indexer:
    base_url: https://sagan-staging.cfapps.io
elasticsearch:
  client:
    index: sagan-staging

---

spring:
  profiles: production
search:
  indexer:
    base_url: https://sagan-production.cfapps.io
elasticsearch:
  client:
    index: sagan-production

---

spring:
  profiles: acceptance
  database:
    url: jdbc:hsqldb:mem:acceptancetestdb
