---
applications:
- name: sagan
  buildpacks:
  - java_buildpack
  instances: 2
  health-check-type: http
  health-check-http-endpoint: /actuator/health/liveness
  timeout: 30
  memory: 2048M
  disk_quota: 1024M
  routes:
  - route: spring.io
  - route: www.spring.io
  - route: sagan-production.cfapps.io
  services:
  - papertrail
  - sagan-db
  - sagan-cache
