project:
  artifactId: sagan-indexer
  name: sagan-indexer
  version: X.X.X.X
  description: sagan-indexer

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:sagan-indexer}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  main:
    sources: sagan.IndexerConfig
  jpa:
    show_sql: false
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl_auto: none

security:
  basic:
    enabled: false
  user:
    password: ${ADMIN_PASSWORD:}

search:
  indexer:
    delay: 0
server:
  port: 9000

elasticsearch:
  client:
    endpoint: ${ELASTICSEARCH_ENDPOINT:http://localhost:9200}
    index: ${ELASTICSEARCH_INDEX:sagan}

# Used to satisfy @Value annotations in GitHubConfiguration and GuideOrganization that are actually only relevant
# for the sagan-site application. This arrangement should be refactored so that keeping these
# entries here on the indexer side is no longer required.
github:
  team:
    id: n/a
  client:
    id: n/a
    secret: n/a
  access:
    token: n/a
  guides:
    owner:
      name: spring-guides
      type: orgs

server:
    tomcat:
        # Write access log to target/logs/access_log.YYYY-MM-DD.log
        # See http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/AccessLogValve.html
        accessLogEnabled: true
        accessLogPattern: '%h %l %u %t "%r" %s %b %{Host}i %{Location}o'
        baseDir: ''
        backgroundProcessorDelay: 1

disqus_shortname: n/a

---

spring:
  profiles: staging
search:
  indexer:
    base_url: http://staging.spring.io

---

spring:
  profiles: production
search:
  indexer:
    base_url: http://spring.io
