project:
  artifactId: sagan-indexer
  name: sagan-indexer
  description: sagan-indexer

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
  spring:
    profiles: ${spring.profiles.active:default}
  app:
    name: ${vcap.application.name:sagan-indexer}:${vcap.application.instance_index:*}
    start: ${vcap.application.start:N/A}

spring:
  main:
    sources: sagan.IndexerApplication
  jpa:
    show_sql: false
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl_auto: none

security:
  basic:
    enabled: false
  user:
    password: ${ADMIN_PASSWORD:}

search:
  indexer:
    delay: 0
    gh_pages:
      domains: projects.spring.io,platform.spring.io,cloud.spring.io

elasticsearch:
  client:
    endpoint: ${ELASTICSEARCH_ENDPOINT:http://localhost:9200}
    index: ${ELASTICSEARCH_INDEX:sagan}

github:

  # Credentials are based on users belonging to a particular GitHub team,
  # by requesting the GitHub API (see github.client configuration keys).
  # This key can be found in the list of teams in your organization
  # See http://developer.github.com/v3/orgs/teams/#list-teams
  team:
    id: ${GITHUB_TEAM_ID:482984}

  # GitHub OAuth application credentials for use when logging into administrative
  # console at /admin. Default 'id' and 'secret' values apply only when running
  # locally, i.e. at http://localhost:8080. Production values must be overridden
  # using GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET, respectively.
  client:
    id: ${GITHUB_CLIENT_ID:fb06c006c2ed62fe9e8b}
    secret: ${GITHUB_CLIENT_SECRET:164264e3f6d70c7c21713b7fa64225cb8d6107b2}

  # This optional property may be assigned using a "personal access token" created
  # at https://github.com/settings/applications. It is used for accessing GitHub's
  # API, even for operations that do not require authorization (e.g. Getting Started
  # Guide repositories). This is done in order to work against higher rate limits
  # (5000req/hour vs. the default 60req/hour without a token). When running the app
  # locally, this lower default is fine. When running the app in production, the
  # token is a must. See http://developer.github.com/v3/#rate-limiting.
  access:
    token: ${GITHUB_ACCESS_TOKEN:}

  # Coordinates for finding guides against the GitHub API
  guides:
    owner:
      name: ${GITHUB_GUIDES_OWNER_NAME:spring-guides} # any GitHub org or user having publicly-readable guide repos
      type: ${GITHUB_GUIDES_OWNER_TYPE:orgs}          # 'users' is the other possible value

server:
  port: 9000

disqus_shortname: n/a

logging:
  level:
    ROOT: WARN
    org.apache.http: WARN
    # turn up to DEBUG to diagnose GitHub API issues
    org.apache.http.headers: WARN
    # turn up to DEBUG to see information about guides as they are fetched and processed
    sagan.guides.support: WARN

---

spring:
  profiles: staging
search:
  indexer:
    base_url: http://staging.spring.io

---

spring:
  profiles: production
search:
  indexer:
    base_url: http://spring.io
